{% set name = "libopus" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xiph/opus/archive/v{{ version }}.tar.gz
  sha256: bf0b97ec7a65890b8db90ef94c4d6c18de12584c3085031953a10986f5917745
  patches:                                          # [ win and arm64 ]
    - 0001-fix-arm-dnn-rtcd-unconditional.patch     # [ win and arm64 ]

build:
  number: 1
  run_exports:
    # seems to be maintaining compatibility across minor versions
    # https://abi-laboratory.pro/tracker/timeline/opus/
    - {{ pin_subpackage('libopus', max_pin='x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make        # [unix]
    - autoconf    # [unix]
    - libtool     # [unix]
    - automake    # [unix]
    - wget        # [unix]
    - cmake       # [win]
    - ninja-base  # [win]

test:
  commands:
    - test ! -f ${PREFIX}/lib/libopus.a            # [unix]
    - test -f ${PREFIX}/lib/libopus${SHLIB_EXT}    # [unix]
    - if not exist %LIBRARY_BIN%\opus.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\opus.lib exit 1   # [win]
    - ldd $PREFIX/lib/libopus${SHLIB_EXT} && ! ldd $PREFIX/lib/libopus${SHLIB_EXT} | grep -qi "not found"   # [linux]
    - otool -L $PREFIX/lib/libopus${SHLIB_EXT} && ! otool -L $PREFIX/lib/libopus${SHLIB_EXT} | grep -qi "not found"   # [osx]

about:
  home: https://opus-codec.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Opus Interactive Audio Codec
  description: |
    Opus is a totally open, royalty-free, highly versatile
    audio codec. Opus is unmatched for interactive speech
    and music transmission over the Internet, but is also
    intended for storage and streaming applications. It is
    standardized by the Internet Engineering Task Force
    (IETF) as RFC 6716 which incorporated technology from
    Skype's SILK codec and Xiph.Org's CELT codec.
  doc_url: https://opus-codec.org/docs
  dev_url: https://opus-codec.org/development
